[package]
authors = ["Zeyla Hellyer <zey@zey.moe>"]
description = "A simple yet effective bucket implementation for Rust."
documentation = "https://docs.rs/hikari"
homepage = "https://github.com/zeyla/hikari"
license = "ISC"
name = "hikari"
readme = "README.md"
repository = "https://github.com/zeyla/hikari.git"
version = "0.1.0"
